<a href="https://colab.research.google.com/github/nkalousis/Linear-Algebra-for-Machine-Learning-and-Data-Science/blob/main/Week1/C1_W1_Lab_1_introduction_to_numpy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Python Matrices and NumPy #

Welcome to your first notebook of this specialization! In this notebook, you will use NumPy to create 2-D arrays and easily compute mathematical operations. NumPy (Numerical Python) is an open-source package that is widely used in science and engineering. Feel fre to skip this notebook, if you are already fluent with NumPy.

**After this assignment you will be able to:**
- Use Jupyter Notebook and its features.
- Use NumPy functions to create arrays and NumPy array operations.
- Use indexing, and slicing for 2-D arrays.
- Find the shape of an array, reshape, and stack horizontally and vertically.

**Instructions**
- You will be using Python 3.
- Follow along the cells using `Shift`+`Enter`. Alternatively, you can press `Run` in the menu.

## Table of Contents ##
[About Jupyter Notebooks](#0)
- [1 - Basics of NumPy](#1)
    - [1.1 - Packages](#1-1)
    - [1.2 - Advantages of using NumPy arrays](#1-2)
    - [1.3 - How to create NumPy arrays](#1-3)
    - [1.4 - More NumPy Arrays](#1-4)
- [2 - Multi-dimensional Arrays](#2)
    - [2.1 - Finding size, shape, dimension](#2-1)
- [3 - Array Math Operations](#3)
    - [3.1 - Multiplying vector with a scalar (broadcasting)](#3-1)
- [4 - Indexing and Slicing](#4)
    - [4.1 - Indexing](#4-1)
    - [4.2 - Slicing](#4-2)
- [5 - Stacking](#5)
- [6 - Exercises](#6)

<a name='0'></a>
## About Jupyter Notebooks ##


Jupyter Notebooks are interactive coding journals that integrate live code, explanatory text, equations, visualizations and other multimedia resources, all in a single document. As a first exercise, run the test snippet below and the print statement cell for "Hello World".

In [2]:
#Run the "Hello World" in the cell below to print "Hello World".
test = "Hello World"

In [3]:
print (test)

Hello World


<a name='1'></a>
# 1 - Basics of NumPy #

NumPy is the main package for scientific computing in Python. It performs a wide variety of advanced mathematical operations with high efficiency. In this practice lab you will learn several key NumPy functions that will help you in future assignments, such as creating arrays, slicing, indexing, reshaping, and stacking.

<a name='1-1'></a>
## 1.1 - Packages ##

Before you get started, you have to import NumPy to load its functions. As you may notice, even though there is no expected output, when you run this cell, the Jupyter Notebook will have imported the package (often referred to as the library) and its functions. Try it for yourself and run the following cell.

In [4]:
import numpy as np

<a name='1-2'></a>
## 1.2 - Advantages of using NumPy arrays ##

Arrays are one of the core data structures of the NumPy library, essential for organizing your data. You can think of them as a grid of values, all of the same type. If you have used Python lists before, you may remember that they are convenient, as you can store different data types. However, Python lists are limited in functions and take up more space and time than NumPy arrays.

NumPy provides an array object that is much faster and more compact than Python lists. Through its extensive API integration, the library offers many built-in functions that make computing much easier in only a few lines of code. This can be a huge advantage when performing math operations on large data.

The array object in NumPy is called `ndarray` meaning 'n-dimensional array'. To begin with, you will use one of the most common array types: the one-dimensional array ('1-D'). A 1-D array represents a standard list of values entirely in one dimension. Remember that in NumPy, all of the elements within the array are of the same type.

In [5]:
one_dimensional_arr = np.array([10, 12])
print(one_dimensional_arr)

[10 12]


<a name='1-3'></a>
## 1.3 - How to create NumPy arrays ##

There are several ways to create an array in NumPy. You can create a 1-D array by simply using the function `array()` which takes in a list of values as an argument, and returns a 1-D array.

In [6]:
# Create and print a numpy array 'a' containing the elements 1, 2, 3.
a = np.array([1, 2, 3])
print(a)

[1 2 3]


Another way to implement an array is using `numpy.arange()`. This function will return an array of evenly spaced values within a given interval. To learn more about the arguments that this function takes, there is a powerful Jupyter Notebooks feature that allows you to access any function's documentation by simply pressing `shift+tab` on your keyboard when clicking on the function. Give it a try for the built-in documentation of `arange()`.

In [7]:
# Create an array with 3 elements, starting from default number 0.
b = np.arange(3)
print(b)

[0 1 2]


In [8]:
# Create an array that starts from integer 1, ends at 20, incremented by 3.
c = np.arange(1, 20, 3)
print(c)

[ 1  4  7 10 13 16 19]


What if you wanted to create an array with five evenly spaced values in the interval from 0 to 100? As you may notice, here you have 3 parameters that the array should take. The start is the number 0, the end is number 100, and 5 is the number of the elements. NumPy has a function that allows you to do specifically this by using `numpy.linspace()`.

In [9]:
lin_spaced_arr = np.linspace(0, 100, 5)
print(lin_spaced_arr)

[  0.  25.  50.  75. 100.]


Did you notice that the output of the function is presented in the float value form (e.g. "0. 25. ")? The reason is that the default type for values in the numpy function is a floating point (`np.float64`). You can easily specify your data type using `dtype`. If you accessed the built-in documentation of the functions, you may have noticed that most functions take in an optional parameter `dtype`. In addition to float, Numpy has several other data types such as 'int', and 'char'.

To change the type to integers, you need to set the dtype to `int`. You can do so, even with the previous functions. Feel free to try it out and modify the cells to output your prefered data type.

In [10]:
lin_spaced_arr_int = np.linspace(0, 100, 5, dtype=int)
print(lin_spaced_arr_int)

[  0  25  50  75 100]


In [11]:
c_int = np.arange(1, 20, 3, dtype=float)
print(c_int)

[ 1.  4.  7. 10. 13. 16. 19.]


In [12]:
b_float = np.arange(3, dtype=float)
print(b_float)

[0. 1. 2.]


In [13]:
char_arr = np.array(['Welcome to Math for ML!'])
print(char_arr)
print(char_arr.dtype) # Prints the data type of the array

['Welcome to Math for ML!']
<U23


Did you notice that the output of the data type of the `char_arr` array is `<U23`?
This means that the string (`'Welcome to Math for ML!'`) is less than a 23-character (23) unicode string (`U`) on a little-endian architecture. You can learn more about data types [here](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.dtypes.html).

<a name='1-4'></a>
## 1.4 - More NumPy Arrays ##

One of the advantages of using NumPy is that you can easily create arrays with built-in functions such as:
- `numpy.ones()` - Returns a new array setting values to one.
- `numpy.zeros()` - Returns a new array setting values to zero.
- `numpy.empty()` - Returns a new uninitialized array.
- `numpy.random.rand()` - Returns a new array with values chosen at random.

In [14]:
# Return a new array with 3 elements of 1.
ones_arr = np.ones(3)
print(ones_arr)

[1. 1. 1.]


In [15]:
# Return a new array with 3 elements of 0.
zeros_arr = np.zeros(3)
print(zeros_arr)

[0. 0. 0.]


In [16]:
# Return a new array with 3 elements without initializing entries.
empt_arr = np.empty(3)
print(empt_arr)

[0. 0. 0.]


In [17]:
# Return a new array with 3 elements between 0 and 1 chosen at random.
rand_arr = np.random.rand(3)
print(rand_arr)

[0.11950981 0.50935235 0.87449073]


<a name='2'></a>
# 2 - Multidimensional Arrays #
With NumPy you can also create arrays with more than one dimension. In the above examples, you encountered 1-D arrays, where you can access their elements using a single index. A multidimensional array has more than one column. Think of a multidimensional array as an excel sheet where each row/column represents a dimension.

![0_Vh-pKXTJsdL-9FT0.png](attachment:0_Vh-pKXTJsdL-9FT0.png)

In [18]:
# Create a 2 dimensional array (2-D)
two_dim_arr = np.array([[1,2,3], [4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


An alternative way to create a multidimensional array is by reshaping the initial 1-D array. Using `numpy.reshape()` you can rearrange elements of the previous array into a new shape.

In [19]:
# 1-D array
one_dim_arr = np.array([1, 2, 3, 4, 5, 6])

# Multi-dimensional array using reshape()
multi_dim_arr = np.reshape(
                one_dim_arr, # the array to be reshaped
               (2,3) # dimensions of the new array
              )
# Print the new 2-D array with two rows and three columns
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]]


<!-- exercise: can you create an array with three rows and 4 columns using np.ones . Whats the dimension, size and shape of the array? -->

<a name='2-1'></a>
## 2.1 - Finding size, shape, dimension. ##

In the future assignments, you will need to know how to find the size, dimension and shape of an array. Using the NumPy built-in functions you can easily identify the followings:
- `ndarray.ndim()` - Returns the number of array dimensions.
- `ndarray.shape()` - Returns the shape of the array. Each number in the tuple denotes the lengths of each corresponding dimension.
- `ndarray.size()` - Counts the number of elements along a given axis. Returns the size of the array.


In [20]:
# Dimension of the 2-D array multi_dim_arr
multi_dim_arr.ndim

2

In [21]:
# Shape of the 2-D array multi_dim_arr
# Returns shape of 2 rows and 3 columns
multi_dim_arr.shape

(2, 3)

In [22]:
# Size of the array multi_dim_arr
# Returns total number of elements
multi_dim_arr.size

6

<a name='3'></a>
# 3 - Array Math Operations #
In this section, you will see that NumPy allows you to quickly perform elementwise addition, substraction, multiplication and division for both 1-D and multidimensional arrays, also known as matrices. The operations are done using the math symbol for each '+', '-', '*'. Recall that addition of python lists works completely differently as it would add (append) two lists together, thus making a longer list, while subtraction and multiplication of python lists do not work.

In [35]:
arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])

# Adding two 1-D arrays
addition = arr_1 + arr_2
print(addition)

# Subtracting two 1-D arrays
subtraction = arr_1 - arr_2
print(subtraction)

# Multiplying two 1-D arrays element by element
multiplication = arr_1 * arr_2
print(multiplication)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


<a name='3-1'></a>
## 3.1 - Multiplying vector with a scalar (broadcasting) ##
Suppose you wanted to convert miles to kilometers using the NumPy array functions that you've learned so far. You can do this by carrying out an operation between an array (miles) and a single number (the conversion rate which is a scalar). Since, 1 mile = 1.6 km, NumPy computes each multiplication within each cell.

This concept is called **broadcasting**, which allows you to perform operations specifically on arrays of different shapes.

In [24]:
vector = np.array([1, 2])
vector * 1.6

array([1.6, 3.2])

![Unknown-2.png](attachment:Unknown-2.png)

<a name='4'></a>
# 4 - Indexing and Slicing #
Indexing is very useful as it allows you to select specific elements from an array. It also lets you select entire rows/columns or planes as you'll see in future assignments for multi-dimensional arrays.

## 4.1 - Indexing ##
Let us select specific elements from the arrays as given.

In [25]:
# Select the third element of the array. Remember the counting starts from 0.
a = ([1, 2, 3, 4, 5])
print(a[2])

# Select the first element of the array.
print(a[0])

3
1


For multi-dimensional arrays, to index a specific element, think of two indices - i selects the row, and j selects the column.

In [26]:
# Indexing on a 2-D array
two_dim = np.array(([1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]))

# Select element number 8 from the 2-D array using indices i, j.
print(two_dim[2][1])

8


<a name='4-2'></a>
## 4.2 - Slicing ##
Slicing gives you a sublist of elements that you specify from the array. The slice notation specifies a start and end value, and copies the list from start up to but not including the end (end-exlusive).

In [27]:
# Slice the array a to give the output [2,3,4]
sliced_arr = a[1:4]
print(sliced_arr)

[2, 3, 4]


In [28]:
# Slice the two_dim array to output the first two rows
sliced_arr_1 = two_dim[0:2]
sliced_arr_1

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
# Similarily, slice the multi-dimensional array two_dim to output the last two rows
sliced_two_dim_rows = two_dim[1:4]
print(sliced_two_dim_rows)

[[4 5 6]
 [7 8 9]]


In [30]:
sliced_two_dim_cols = two_dim[:,1]
print(sliced_two_dim_cols)

[2 5 8]


<a name='5'></a>
# 5 - Stacking #
Finally, stacking is a feature of NumPy that leads to increased customization of arrays. It basically means to join two or more arrays, either horizontally or vertically, meaning that it is done along a new axis.

- `vstack` - stacks vertically
- `hstack` - stacks horizontally
- `hsplit` - splits an array into several smaller arrays

In [31]:
a1 = np.array([[1,1],
               [2,2]])
a2 = np.array([[3,3],
              [4,4]])
print(a1)
print(a2)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [32]:
# Stack arrays vertically
vert_stack = np.vstack((a1, a2))
print(vert_stack)


[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [33]:
# Stack arrays horizontally
horz_stack = np.hstack((a1, a2))
print(horz_stack)

[[1 1 3 3]
 [2 2 4 4]]


In [37]:
import ipywidgets as widgets
from ipywidgets import interact, Dropdown


question1 = "\033[1mSelect one of the options given:"
solution1 = {'A':'\033[91mNot quite. While both functions are used to create empty arrays, np.zeros() is initialized with the value 0.',
'B':"\033[91mNot quite. np.zeros() is inialized, and it gives an output of 0's.",
'C':"\033[91mNot quite. Most often, np.empty() is faster since it is not initialized.",
'D':''' \033[92mTrue! np.empty() creates an array with uninitialized elements from available memory space and may be faster to execute.'''}



def mcq(question, solution):
    s = ''
#     print(question)
    print("\033[1mPlease select the correct option:")
    answer_w = Dropdown(options = solution.keys(), value=None, layout=widgets.Layout(width='25%'))

    @interact(Answer = answer_w)
    def print_city(Answer):
        if(Answer != None):
            s = solution[Answer]
#             print("\n")
            print(s)

<a name='6'></a>
## Exercises ##
Well done! Now, from what you learned today, try to answer the following question.

### Question 1 ###
Is there a difference between `np.zeros()` and `np.empty()`? Select one of the options given:
- A. No difference, they both output arrays of zeros.
- B. `np.zeros()` is not initialized, but gives an output of zeros.
- C. `np.zeros()` is faster to execute than `np.empty()`.
- D. `np.empty()` outputs an uninitialized array, but `np.zeros` outputs an initialized array of value zero.

In [40]:
# Run this cell to select your answer

q1 = mcq(question1, solution1)

Please select the correct option:


interactive(children=(Dropdown(description='Answer', layout=Layout(width='25%'), options=('A', 'B', 'C', 'D'),…

Congratulations on finishing your first notebook of this specialization!